const bestSellerData = [
  {
    id: 1,
    bgcolor: 'dark',
    color: 'warning',
    headline: 'SmartPhones and Earbuds',
    image1: "bestseller1.png",
    image2: "bestseller2.png",
    image3: "bestseller3.png",
    title1: "Apple iPhone 14 Pro Max",
    title2: "Nothing Phone 1",
    title3: "Bose QuietComfort II Earbuds",
    description1: "",
    description2: "",
    description3: "",
    logo: "mainlogo.png",
    category1: "Tech Gadgets",
    category2: "Tech Gadgets",
    category3: "Tech Gadgets",
    timestamp1: "3d",
    timestamp2: "4d",
    timestamp3: "5d",
  },
  {
    id: 2,
    bgcolor: 'warning',
    color: 'dark',
    headline: 'Smart Watches, Wearables and Tablets',
    image1: "bestseller4.png",
    image2: "bestseller5.png",
    image3: "bestseller6.png",
    title1: "Apple Watch Ultra",
    title2: "Oura Ring Gen 3 Horizon",
    title3: "Samsung Galaxy Tab S8 Plus",
    description1: "",
    description2: "",
    description3: "",
    logo: "mainlogo.png",
    category1: "Tech Gadgets",
    category2: "Tech Gadgets",
    category3: "Tech Gadgets",
    timestamp1: "3d",
    timestamp2: "4d",
    timestamp3: "5d",
  },
  {
    id: 3,
    bgcolor: 'dark',
    color: 'warning',
    headline: 'Laptops, TVs and Gaming KeyBoarsds',
    image1: "bestseller7.png",
    image2: "bestseller8.png",
    image3: "bestseller9.png",
    title1: "Apple MacBook Air M2",
    title2: "Samsung Neo QLED 8K QN800B TV",
    title3: "Wooting 60HE Gaming Keyboard",
    description1: "",
    description2: "",
    description3: "",
    logo: "mainlogo.png",
    category1: "Tech Gadgets",
    category2: "Tech Gadgets",
    category3: "Tech Gadgets",
    timestamp1: "3d",
    timestamp2: "4d",
    timestamp3: "5d",
  },
  {
    id: 4,
    bgcolor: 'warning',
    color: 'dark',
    headline: 'Gaming Headsets, Mouse and Robot Cleaners',
    image1: "bestseller10.png",
    image2: "bestseller11.png",
    image3: "bestseller12.png",
    title1: "Logitech MX Master 3S",
    title2: "Drop + EPOS PC38X Gaming Headset",
    title3: "Roomba j7+",
    description1: "",
    description2: "",
    description3: "",
    logo: "mainlogo.png",
    category1: "Tech Gadgets",
    category2: "Tech Gadgets",
    category3: "Tech Gadgets",
    timestamp1: "3d",
    timestamp2: "4d",
    timestamp3: "5d",
  },
];

export default bestSellerData;
