const product = [
  {
    id: 1,
    mainbg1color: '',
    mainbg2color: 'white',
    card1color: "white",
    bg1color: "dark",
    card2color: "dark",
    bg2color: "white",
    heading1: "Tonal",
    heading2: "Hisense 8K ULED Roku TV",
    subheading1: "",
    subheading2: "",
    image1: "product_1.jpg",
    image2: "product_2.jpg",
  },
  {
    id: 2,
    mainbg1color: 'white',
    mainbg2color: '',
    card1color: "dark",
    bg1color: "white",
    card2color: "white",
    bg2color: "primary",
    heading1: "Google - Pixel 6 Pro",
    heading2: "Oura Ring Generation 3",
    subheading1: "",
    subheading2: "",
    image1: "product_3.jpg",
    image2: "product_4.jpg",
  },
  {
    id: 3,
    mainbg1color: 'white',
    mainbg2color: 'white',
    card1color: "white",
    bg1color: "white",
    card2color: "white",
    bg2color: "white",
    heading1: "Dyson Purifier Humidify",
    heading2: "Nanoleaf Lines",
    subheading1: "",
    subheading2: "",
    image1: "product_5.jpg",
    image2: "product_6.jpg",
  },
  {
    id: 4,
    mainbg1color: '',
    mainbg2color: 'white',
    card1color: "white",
    bg1color: "dark",
    card2color: "dark",
    bg2color: "white",
    heading1: "Bartesian",
    heading2: "Tempo Move",
    subheading1: "",
    subheading2: "",
    image1: "product_7.jpg",
    image2: "product_8.jpg",
  },
  {
    id: 5,
    mainbg1color: 'white',
    mainbg2color: '',
    card1color: "dark",
    bg1color: "white",
    card2color: "white",
    bg2color: "primary",
    heading1: "Apple M1 Macbook Pro",
    heading2: "VIVE Flow",
    subheading1: "",
    subheading2: "",
    image1: "product_9.jpg",
    image2: "product_10.jpg",
  },
  {
    id: 6,
    mainbg1color: 'white',
    mainbg2color: 'white',
    card1color: "white",
    bg1color: "white",
    card2color: "white",
    bg2color: "white",
    heading1: "Osma Pro pre-order",
    heading2: "LARQ Pitcher PureVis™",
    subheading1: "",
    subheading2: "",
    image1: "product_11.jpg",
    image2: "product_12.jpg",
  },
];

export default product;
